### ISSUE TITLE
Support also range engine version format

### ISSUE THREAD

**Issue by vmatyusGitHub** [voxpelli/node-installed-check-core#18]
I have troubles when I specify the node engine version in a range form: `^12 || ^14 || ^16`

I am using [installed-check](https://www.npmjs.com/package/installed-check) for dependency checking.

When I set the engine versions to use range format `^12 || ^14 || ^16` the check throws the following error:

```bash
Dependency errors:

<dependency>: Narrower "node" engine requirement needed: >=10
Combined "node" engine requirement needs to be narrower: ^12.0.0
```

The problem is the [intersect func](https://www.npmjs.com/package/@voxpelli/semver-set) returns only the lowest common denominator of versions. So the check [here](https://github.com/voxpelli/node-installed-check-core/blob/4242ed5cffabbcfb3ab50ba6df786bf06e4a6197/lib/check-engine-versions.js#L64) is failing, because
`^12.0.0 != ^12 || ^14 || ^16`.

I think the intersect works correctly and finds a working version, so my package and the dependency package are compatible with each other. But the checker throws an error to this valid case.

**Comment by voxpelli** [comment]
It uses a complete rewrite of semver-set, which has tests for those cases: https://github.com/voxpelli/semver-set/blob/master/test/main.spec.js

**Comment by vmatyusGitHub** [comment]
I tried it out, it has the same problem still.
The `semverIntersect` function works properly, the problem is only with the cooperation with the `installed-check` tool.
Failing at the same point `else if (intersection !== engines[engine]` => `^12.0.0 != ^12 || ^14 || ^16`

**Comment by voxpelli** [comment]
Interesting, thanks a lot @vmatyusGitHub! Will check it out

**Comment by voxpelli** [comment]
Sorry for almost taking three years to fix this 🙈

**Comment by vmatyusGitHub** [comment]
Thank you for your work! :)
